root = "."
tmp_dir = "tmp"

[build]
bin = "./tmp/main"
cmd = "go build -o ./tmp/main ./cmd/server"
delay = 1000
exclude_dir = ["tmp", "vendor", ".git"]
include_ext = ["go", "html", "tmpl"]
kill_delay = "0s"

[log]
time = false

[misc]
clean_on_exit = true
